// factory.mjs — Octo Bot Factory
// Spawns new Telegram bots programmatically via Managed Bots API

import { execFile } from 'child_process';
import { promisify } from 'util';
import { mkdir, writeFile, copyFile, readFile } from 'fs/promises';
import { existsSync, mkdirSync } from 'fs';
import { join } from 'path';

const execFileAsync = promisify(execFile);

const BOT_CIRCUS_DIR = '/root/bot-circus';
const CIRCUS_IDENTITY_DIR = '/root/.circus';
const MANAGED_BOTS_FILE = `${CIRCUS_IDENTITY_DIR}/managed-bots.json`;

/**
 * Get a managed bot token
 * Note: Telegram's getManagedBotToken requires Business Mode connection.
 * For standalone bot spawning, tokens must be obtained via @BotFather manually.
 * This function returns null — caller should prompt user for token.
 */
export async function getManagedBotToken(octoToken, botName) {
  // Uses Telegram Business Mode connection
  const BUSINESS_CONNECTION_ID = process.env.TELEGRAM_BUSINESS_CONNECTION_ID || 'cvIc6aYYMVEcBQAA8cFOIdPVPF8';
  
  const url = `https://api.telegram.org/bot${octoToken}/getManagedBotToken`;
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ business_connection_id: BUSINESS_CONNECTION_ID })
  });
  
  const data = await response.json();
  console.log('[factory] getManagedBotToken response:', JSON.stringify(data));
  
  if (!data.ok) {
    throw new Error('Telegram API error: ' + (data.description || JSON.stringify(data)));
  }
  
  return data.result?.token;
}

/**
 * Get info about a bot token (username, id)
 */
export async function getBotInfo(token) {
  const res = await fetch(`https://api.telegram.org/bot${token}/getMe`);
  const data = await res.json();
  if (!data.ok) throw new Error(`getMe failed: ${data.description}`);
  return data.result; // { id, username, first_name, ... }
}

/**
 * Load managed bots manifest
 */
export async function loadManagedBots() {
  if (!existsSync(MANAGED_BOTS_FILE)) return [];
  const content = await readFile(MANAGED_BOTS_FILE, 'utf8');
  return JSON.parse(content);
}

/**
 * Save managed bots manifest
 */
export async function saveManagedBots(bots) {
  await writeFile(MANAGED_BOTS_FILE, JSON.stringify(bots, null, 2));
}

/**
 * Generate performer directory for a new bot
 * type: 'general' (Claude-powered) or 'specialist' (lightweight hardcoded)
 */
export async function generatePerformer(name, token, type, rolePrompt, allowedUserId) {
  const safeName = name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
  const performerDir = join(BOT_CIRCUS_DIR, 'performers', safeName);

  if (existsSync(performerDir)) {
    throw new Error(`Performer "${safeName}" already exists at ${performerDir}`);
  }

  await mkdir(performerDir, { recursive: true });
  await mkdir(join(performerDir, 'data'), { recursive: true });
  await mkdir(join(performerDir, 'memory'), { recursive: true });

  if (type === 'general') {
    await generateGeneralPerformer(performerDir, safeName, name, rolePrompt);
  } else {
    await generateSpecialistPerformer(performerDir, safeName, name, rolePrompt);
  }

  // Write .env
  await writeFile(join(performerDir, '.env'), [
    `TELEGRAM_BOT_TOKEN=${token}`,
    `ALLOWED_USER_ID=${allowedUserId}`,
    `BOT_NAME=${name}`,
    `BOT_ROLE=${type}`,
    `ROLE_PROMPT=${rolePrompt}`,
    `CLAUDE_CLI_PATH=/root/.local/bin/claude`,
    `CLAUDE_WORKING_DIR=${performerDir}`,
    `CLAUDE_TIMEOUT=300000`,
    `CIRCUS_URL=http://localhost:6200`,
  ].join('\n'));

  // Write package.json
  await writeFile(join(performerDir, 'package.json'), JSON.stringify({
    name: `${safeName}-bot`,
    version: '1.0.0',
    type: 'module',
    main: 'bot.mjs',
    scripts: { start: 'node bot.mjs' },
    dependencies: {
      grammy: '^1.42.0',
      dotenv: '^16.4.5'
    }
  }, null, 2));

  // Write IDENTITY.md
  await writeFile(join(performerDir, 'IDENTITY.md'), `# ${name}\n\nType: ${type}\nRole: ${rolePrompt}\nCreated by Octo Bot Factory\n`);

  // Write MEMORY.md
  await writeFile(join(performerDir, 'MEMORY.md'), `# ${name} Memory\n\n(empty — bot just spawned)\n`);

  return { safeName, performerDir };
}

async function generateGeneralPerformer(dir, safeName, displayName, rolePrompt) {
  const botCode = `#!/usr/bin/env node
// ${displayName} — General-purpose bot (Claude-powered)
// Generated by Octo Bot Factory

import { Bot } from 'grammy';
import { config } from 'dotenv';
import { spawn } from 'child_process';

config({ override: true });

const bot = new Bot(process.env.TELEGRAM_BOT_TOKEN);
const ALLOWED_USER_ID = parseInt(process.env.ALLOWED_USER_ID, 10);
const ROLE_PROMPT = process.env.ROLE_PROMPT || 'You are a helpful assistant.';
const BOT_NAME = process.env.BOT_NAME || '${displayName}';

function isAllowed(ctx) {
  return ctx.from?.id === ALLOWED_USER_ID;
}

bot.on('message:text', async (ctx) => {
  if (!isAllowed(ctx)) return ctx.reply('Access denied.');

  const userMsg = ctx.message.text;

  // Send to Claude CLI
  const claude = spawn('/root/.local/bin/claude', [
    '--print', '--output-format', 'text',
    '--system', ROLE_PROMPT,
    userMsg
  ], {
    cwd: process.env.CLAUDE_WORKING_DIR || __dirname,
    timeout: 300000
  });

  let output = '';
  let error = '';
  claude.stdout.on('data', d => output += d);
  claude.stderr.on('data', d => error += d);

  await new Promise((resolve) => claude.on('close', resolve));

  const reply = output.trim() || error.trim() || 'No response.';
  await ctx.reply(reply.slice(0, 4096));
});

bot.command('start', ctx => ctx.reply(\`Hi! I'm ${displayName}. \${ROLE_PROMPT.slice(0, 200)}\`));
bot.command('help', ctx => ctx.reply(\`Bot: ${displayName}\\nRole: \${ROLE_PROMPT}\`));

bot.catch(err => console.error('[${safeName}] Error:', err));

bot.start({ drop_pending_updates: true });
console.log('[${safeName}] Started (general/Claude-powered)');
`;
  await writeFile(join(dir, 'bot.mjs'), botCode);
}

async function generateSpecialistPerformer(dir, safeName, displayName, rolePrompt) {
  const botCode = `#!/usr/bin/env node
// ${displayName} — Specialist bot (lightweight, hardcoded)
// Generated by Octo Bot Factory
// Role: ${rolePrompt}

import { Bot } from 'grammy';
import { config } from 'dotenv';

config({ override: true });

const bot = new Bot(process.env.TELEGRAM_BOT_TOKEN);
const ALLOWED_USER_ID = parseInt(process.env.ALLOWED_USER_ID, 10);
const BOT_NAME = process.env.BOT_NAME || '${displayName}';
const ROLE_PROMPT = \`${rolePrompt}\`;

// TODO: Replace with specialist logic
// This is a scaffold — add your specific handler logic here

bot.on('message:text', async (ctx) => {
  if (ctx.from?.id !== ALLOWED_USER_ID) return;

  const text = ctx.message.text.toLowerCase();

  // Add your specialist logic here
  await ctx.reply(\`[\${BOT_NAME}] Received: \${ctx.message.text}\\n\\nRole: \${ROLE_PROMPT}\\n\\n(Specialist logic not yet implemented — edit bot.mjs)\`);
});

bot.command('start', ctx => ctx.reply(\`${displayName} online. Role: \${ROLE_PROMPT}\`));
bot.command('status', ctx => ctx.reply(\`✅ \${BOT_NAME} running\`));

bot.catch(err => console.error('[${safeName}] Error:', err));

bot.start({ drop_pending_updates: true });
console.log('[${safeName}] Started (specialist)');
`;
  await writeFile(join(dir, 'bot.mjs'), botCode);
}

/**
 * Install npm dependencies in performer directory
 */
export async function installDeps(performerDir) {
  await execFileAsync('npm', ['install', '--prefer-offline'], {
    cwd: performerDir,
    timeout: 60000
  });
}

/**
 * Start bot with PM2
 */
export async function launchPM2(safeName, performerDir) {
  await execFileAsync('pm2', [
    'start', join(performerDir, 'bot.mjs'),
    '--name', `${safeName}-bot`,
    '--cwd', performerDir,
    '--interpreter', 'node'
  ], { timeout: 15000 });

  // Save PM2 state
  await execFileAsync('pm2', ['save'], { timeout: 10000 });
}

/**
 * Save bot record to managed-bots manifest
 */
export async function recordManagedBot(record) {
  const bots = await loadManagedBots();
  bots.push({
    ...record,
    created_at: new Date().toISOString()
  });
  await saveManagedBots(bots);
}

/**
 * Main factory function — orchestrates everything
 */
export async function spawnBot({ octoToken, name, type, rolePrompt, allowedUserId }) {
  console.log(`[factory] Spawning ${type} bot: ${name}`);

  // 1. Get token
  let token = await getManagedBotToken(octoToken, name);
  if (!token) {
    throw new Error(`Token required. Create a bot via @BotFather:\n1. Message @BotFather\n2. Send /newbot\n3. Follow prompts\n4. Copy the token and reply here with: "token is [YOUR_TOKEN]"`);
  }

  // 2. Get bot info (username)
  const botInfo = await getBotInfo(token);

  // 3. Generate performer files
  const { safeName, performerDir } = await generatePerformer(name, token, type, rolePrompt, allowedUserId);

  // 4. Install deps
  await installDeps(performerDir);

  // 5. Launch with PM2
  await launchPM2(safeName, performerDir);

  // 6. Record in manifest
  await recordManagedBot({
    name,
    safeName,
    username: botInfo.username,
    telegram_id: botInfo.id,
    type,
    rolePrompt,
    performerDir
  });

  return {
    name,
    username: `@${botInfo.username}`,
    type,
    pm2Name: `${safeName}-bot`,
    performerDir
  };
}

/**
 * Stop and deregister a managed bot
 */
export async function killBot(safeName) {
  // PM2 stop
  try {
    await execFileAsync('pm2', ['stop', `${safeName}-bot`], { timeout: 10000 });
    await execFileAsync('pm2', ['delete', `${safeName}-bot`], { timeout: 10000 });
  } catch (_) {}

  // Remove from manifest
  const bots = await loadManagedBots();
  const updated = bots.filter(b => b.safeName !== safeName);
  await saveManagedBots(updated);
}
