#!/usr/bin/env node
// TestBot — Specialist disk usage monitor
// Generated by Octo Bot Factory

import { Bot } from 'grammy';
import { config } from 'dotenv';
import { execFile } from 'child_process';
import { promisify } from 'util';

config({ override: true });

const execFileAsync = promisify(execFile);
const bot = new Bot(process.env.TELEGRAM_BOT_TOKEN);
const ALLOWED_USER_ID = parseInt(process.env.ALLOWED_USER_ID, 10);
const BOT_NAME = process.env.BOT_NAME || 'TestBot';

// Alert threshold
const ALERT_THRESHOLD_PCT = parseInt(process.env.ALERT_THRESHOLD_PCT || '80', 10);

function isAllowed(ctx) {
  return ctx.from?.id === ALLOWED_USER_ID;
}

async function getDiskUsage() {
  try {
    const { stdout } = await execFileAsync('df', ['-h', '/'], { timeout: 5000 });
    const lines = stdout.trim().split('\n');
    const dataLine = lines[1];
    const parts = dataLine.split(/\s+/);
    const usePct = parseInt(parts[4], 10); // e.g. 72%
    return {
      filesystem: parts[0],
      size: parts[1],
      used: parts[2],
      avail: parts[3],
      usePct,
      mountpoint: parts[5],
      raw: stdout
    };
  } catch (err) {
    return null;
  }
}

function formatDiskReport(d) {
  const bar = '█'.repeat(Math.round(d.usePct / 10)) + '░'.repeat(10 - Math.round(d.usePct / 10));
  const emoji = d.usePct >= 90 ? '🔴' : d.usePct >= 80 ? '🟡' : '🟢';
  return [
    `💾 *Disk Usage Report*`,
    ``,
    `${emoji} ${d.usePct}% used`,
    `${bar}`,
    ``,
    `Used: ${d.used} / ${d.size}`,
    `Free: ${d.avail}`,
    `Mount: ${d.mountpoint}`,
  ].join('\n');
}

// Check and alert if over threshold
async function checkAndAlert() {
  const d = await getDiskUsage();
  if (!d) return;
  if (d.usePct >= ALERT_THRESHOLD_PCT) {
    try {
      await bot.api.sendMessage(
        ALLOWED_USER_ID,
        `⚠️ *Disk Alert*\n\nUsage at ${d.usePct}% — above ${ALERT_THRESHOLD_PCT}% threshold.\nFree: ${d.avail}\n\n— ${BOT_NAME}`,
        { parse_mode: 'Markdown' }
      );
    } catch (err) {
      console.error('[testbot] Alert send failed:', err.message);
    }
  }
}

// Commands
bot.command('start', async ctx => {
  if (!isAllowed(ctx)) return;
  await ctx.reply(`👋 ${BOT_NAME} online.\n\nCommands:\n/disk — check disk usage\n/status — system status\n\nI alert you when disk exceeds ${ALERT_THRESHOLD_PCT}%.`);
});

bot.command('disk', async ctx => {
  if (!isAllowed(ctx)) return;
  const d = await getDiskUsage();
  if (!d) return ctx.reply('❌ Could not read disk usage.');
  await ctx.reply(formatDiskReport(d), { parse_mode: 'Markdown' });
});

bot.command('status', async ctx => {
  if (!isAllowed(ctx)) return;
  const d = await getDiskUsage();
  if (!d) return ctx.reply('❌ Could not read status.');

  // Also get memory
  let memLine = '';
  try {
    const { stdout } = await execFileAsync('free', ['-h'], { timeout: 5000 });
    const memParts = stdout.split('\n')[1].split(/\s+/);
    memLine = `\nRAM: ${memParts[2]} used / ${memParts[1]} total`;
  } catch (_) {}

  await ctx.reply(
    `📊 *${BOT_NAME} Status*\n\nDisk: ${d.usePct}% (${d.used}/${d.size})${memLine}\n\n— ${BOT_NAME}`,
    { parse_mode: 'Markdown' }
  );
});

// Natural language
bot.on('message:text', async ctx => {
  if (!isAllowed(ctx)) return;
  const text = ctx.message.text.toLowerCase();
  if (/disk|storage|space|drive/.test(text)) {
    const d = await getDiskUsage();
    if (!d) return ctx.reply('❌ Could not read disk usage.');
    await ctx.reply(formatDiskReport(d), { parse_mode: 'Markdown' });
  } else {
    await ctx.reply(`Use /disk to check disk usage, /status for system overview.\n— ${BOT_NAME}`);
  }
});

bot.catch(err => console.error('[testbot] Error:', err.message));

// Check disk every 30 minutes
setInterval(() => checkAndAlert().catch(console.error), 30 * 60 * 1000);

bot.start({ drop_pending_updates: true });
console.log(`[${BOT_NAME}] Started — monitoring disk at ${ALERT_THRESHOLD_PCT}% threshold`);
